Endpoint para atualizar Pedido
pangolin-do-golang/tech-challenge pull request #44
Opened 2024-07-22 23:55 UTC by jefersonhuan

## Why

Endpoint que atende ao requisito de atualizar o Pedido/e também como webhook para confirmar/negar o pagamento.

## Pull request type
- [x] New resource
- [ ] Update resource
- [ ] Bugfix
- [ ] Other (please describe):

## Rollback plan
- [x] Revert this PR
- [ ] Other (please, specify):

2024-07-25 21:38 UTC, sirioneto requested changes

2024-07-25 21:38 UTC, sirioneto commented on internal/core/order/order_service.go
> +func (s *Service) Update(id uuid.UUID, status string) (*Order, error) {
Considerando o requisito de ordenação da listagem de pedidos por status, não faria mais sentido termos uma referência numérica pra ele?

Posso fazer demais alterações no branch da listagem, apenas para ter em mente neste fluxo também.

Além disso, acho prudente alterar o recurso para UpdateStatus, para não dar a entender que todo o pedido pode ser alterado.

2024-07-25 21:38 UTC, sirioneto commented on internal/adapters/rest/controller/abstract_controller.go
> +func (ctrl *AbstractController) Error(c *gin.Context, err error) {
Implementação interessante, notei alguns `http.StatusInternalServerError` (500) nas controllers de cart e product, que poderiam ser substituidos por essa função.

2024-07-25 21:38 UTC, sirioneto commented on internal/adapters/rest/handler/order.go
> +	router.PATCH("/orders/:id", orderController.Update)
Interessante ajustar para um endpoint que indique a alteração do status somente ex: `/orders/status/:id`

2024-07-25 21:38 UTC, sirioneto commented on internal/core/order/order.go
> +	StatusPending   = "PENDING"
Considerando o requisito de ordenação da listagem de pedidos por status, não faria mais sentido termos uma referência numérica para esse atributo?

2024-07-25 21:38 UTC, sirioneto commented on docs/docs.go
> +                    "application/json"
Possível conflito com a estrutura do branch master? Atualmente usa o path `core`.

2024-07-25 22:28 UTC, jefersonhuan commented on internal/core/order/order_service.go
> +func (s *Service) Update(id uuid.UUID, status string) (*Order, error) {
Faz sentido considerar como número, mas eu acho que nesse contexto seria melhor fazer um [switch/case no psql](https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-CASE), saca? Ficaria mais ou menos assim:
```sql
SELECT id, client_id, status, ...
CASE status
WHEN 'PENDING' THEN 1
WHEN 'APPROVED' THEN 2
ELSE 0 status_weight
FROM order
ORDER BY status_weight DESC/ASC;
```

Acha viável para o quê tá fazendo?

2024-07-25 22:29 UTC, jefersonhuan commented on internal/adapters/rest/controller/abstract_controller.go
> +func (ctrl *AbstractController) Error(c *gin.Context, err error) {
Boa, vou rever eles

2024-07-25 22:30 UTC, jefersonhuan commented on internal/adapters/rest/handler/order.go
> +	router.PATCH("/orders/:id", orderController.Update)
Vou considerar como do Pedido mesmo, já que o somente o status é atualizável. Mas vou alterar os nomes pra isso ficar claro

2024-07-27 17:51 UTC, sirioneto commented on internal/core/order/order_service.go
> +func (s *Service) Update(id uuid.UUID, status string) (*Order, error) {
@jefersonhuan  Pode ser também, é tranquilo de fazer usando a função `raw` do gorm. Não comentei antes mas sugeri usarmos uma referência numérica (um tinyint unsigned, por exemplo) por questão de tamanho e indexação da coluna, e caso precisemos mudar a prioridade, poderíamos usar a mesma estratégia que sugeriu.

Mas por hora concordo que não é algo essencial. Podemos tratar como uma melhoria isolada nas próximas fazes. O que acha?

2024-07-27 18:38 UTC, sirioneto reviewed
Só esses detalhes finais.

2024-07-27 18:38 UTC, sirioneto commented on internal/adapters/rest/controller/order_controller.go
> +// @Router /orders/:id [patch]
Só um ajuste pra agrupar com a outra rota de mesmo endpoint na documentação. Também notei que esse recurso em específico retorna erro de CORS ao testar pela documentação do swagger (mesmo com middleware de CORS aplicado), os demais recursos funcionam corretamente.

```suggestion
// @Router /orders/{id} [patch]
```

2024-07-27 18:38 UTC, sirioneto commented on internal/core/order/order.go
> +	return ErrInvalidStatus
Nos testes da API que fiz sempre retorna erro de validação aqui, acredito que aqui deveria ter outro retorno.

2024-07-27 22:57 UTC, jefersonhuan commented on internal/adapters/rest/controller/order_controller.go
> +// @Router /orders/:id [patch]
Eita, tô acostumado com a semântica do Fiber 😅

2024-07-27 23:05 UTC, jefersonhuan commented on internal/core/order/order.go
> +	return ErrInvalidStatus
Corrigido!

2024-07-27 23:07 UTC, jefersonhuan commented on internal/core/order/order_service.go
> +func (s *Service) Update(id uuid.UUID, status string) (*Order, error) {
Eu acho válido deixar como está agora, até porque não sabemos qual o rumo das coisas.

2024-07-29 02:34 UTC, sirioneto approved these changes
Apenas verificar uso da coluna `deleted_at` no service de produto (func GetById) na criação de pedido a partir do carrinho.
![image](https://github.com/user-attachments/assets/b7ba0d5e-ac79-48e9-a832-e8c06db61b60)

2024-07-30 00:56 UTC, merged